namespace Application.Interfaces
{
    public interface IPasswordHasher
    {
        /// <summary>
        /// Generates a secure hash for the specified password.
        /// </summary>
        /// <param name="password">The plain text password to hash. Cannot be null or empty.</param>
        /// <returns>A string containing the hashed representation of the password.</returns>
        string HashPassword(string password);

        /// <summary>
        /// Verifies whether the specified password matches the provided hashed password.
        /// </summary>
        /// <param name="password">The plain text password to verify.</param>
        /// <param name="hashedPassword">The hashed password to compare against. Must be a valid hash generated by the corresponding hashing
        /// algorithm.</param>
        /// <returns>true if the password matches the hashed password; otherwise, false.</returns>
        bool VerifyPassword(string password, string hashedPassword);
    }
}
